version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.15
  aws-ecs: circleci/aws-ecs@2.0.0

jobs:
  test_backend:
    docker:
      - image: circleci/ruby:2.6.6-stretch-node
        environment:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
      - image: circleci/mysql:5.7.30

    working_directory: ~/repo

    steps:
      - checkout

      # restore gem from cache
      - restore_cache:
          keys:
            - gem-cache-v1-{{ checksum "~/repo/rails/Gemfile.lock" }}
            - gem-cache-v1-
          working_directory: ~/repo/rails

      # gem install
      - run:
          command: |
            gem install bundler
            bundle config set path 'vendor/bundle'
            bundle install --jobs=4 --retry=3
          working_directory: ~/repo/rails

      - save_cache:
          key: gem-cache-v1-{{ checksum "~/repo/rails/Gemfile.lock" }}
          paths:
            - ~/repo/rails/vendor/bundle
          working_directory: ~/repo/rails

      # Database setup
      - run:
          command: bundle exec rails db:create
          working_directory: ~/repo/rails
      - run:
          command: bundle exec rails db:migrate
          working_directory: ~/repo/rails

      - run:
          name: create directory to store test results
          command: mkdir /tmp/test-results
          working_directory: ~/repo/rails

      - run:
          name: RSpec
          command: |
            bundle exec rspec $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings) \
              || (printf "====== RETRYING...\n\n\n"; bundle exec rspec --only-failures)
          working_directory: ~/repo/rails

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
      - store_artifacts:
          path: /home/circleci/repo/tmp/screenshots

  test_frontend:
    docker:
      - image: circleci/node:14.3
        environment:
          NODE_ENV: test

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "~/repo/nuxt/package.json" }}
          working_directory: ~/repo/nuxt
      - run:
          name: install-packages
          command: npm install
          working_directory: ~/repo/nuxt
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "~/repo/nuxt/package.json" }}
          working_directory: ~/repo/nuxt
      - run:
          name: test
          command: npm run test
          working_directory: ~/repo/nuxt

  build_and_push_image_backend:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          account-url: AWS_ACCOUNT_URL
          repo: "rails-api"
          region: AWS_REGION
          tag: "${CIRCLE_SHA1}"
          path: ./rails/

  build_and_push_image_frontend:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          account-url: AWS_ACCOUNT_URL
          repo: "rails-api-nuxt"
          region: AWS_REGION
          tag: "${CIRCLE_SHA1}"
          path: ./nuxt/

workflows:
  version: 2
  test:
    jobs:
      - test_backend:
          filters:
            branches:
              ignore: main
      - test_frontend:
          filters:
            branches:
              ignore: main
  test_and_deploy:
    jobs:
      - test_backend:
          filters:
            branches:
              only: main
      - test_frontend:
          filters:
            branches:
              only: main
      - build_and_push_image_backend:
          requires:
            - test_frontend
            - test_backend
          filters:
            branches:
              only: main
      - build_and_push_image_frontend:
          requires:
            - test_frontend
            - test_backend
          filters:
            branches:
              only: main
      - aws-ecs/deploy-service-update:
          requires:
            - build_and_push_image_backend
            - build_and_push_image_frontend
          family: "rails-api-backend"
          service-name: "rails-back"
          cluster-name: "rails-backend"
          container-image-name-updates: "container=rails,tag=${CIRCLE_SHA1}"
          filters:
            branches:
              only: main
      - aws-ecs/deploy-service-update:
          requires:
            - build_and_push_image_backend
            - build_and_push_image_frontend
          family: "rails-api-nuxt"
          service-name: "front-service"
          cluster-name: "rails-api-nuxt"
          container-image-name-updates: "container=rails-nuxt-container,tag=${CIRCLE_SHA1}"
          filters:
            branches:
              only: main
